<?php namespace App\Repositories;


use App\Repositories\Eloquent\Repository;

class QuotaRepository extends Repository {

    /**
     * Specify Model class name
     *
     * @return mixed
     */
    public function model()
    {
        return 'App\Quota';
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }


}